apiVersion: v1
kind: Secret
metadata:
  name: demo-avp
  namespace: avp-test
  annotations:
    avp.kubernetes.io/path: secret/data/kv/app/prod
type: Opaque
stringData:
  username: <DB_USERNAME>
  password: <DB_PASSWORD>
